### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by zoff99** [TokTok/jvm-toxcore-c#9]
https://travis-ci.org/TokTok/jvm-toxcore-c/jobs/173011835

![unbenannt](https://cloud.githubusercontent.com/assets/6833516/21265080/ea645722-c39f-11e6-8b80-31473c0a59d8.PNG)

librt not found? is that ok?

**Comment by zoff99** [comment]
i can't seem to generate to *.so files for android.
also the tox4j.jar file does not contain all classes.

**Comment by iphydf** [comment]
Can you post a full build log? The screenshot you posted looks fine. Those are "configure" messages trying to detect capabilities of the environment.

**Comment by zoff99** [comment]
this is your own travis build, i pasted the link to the log. see my first post.
can you help me getting this to build and to make the *.jar file

here is the link again:
https://travis-ci.org/TokTok/jvm-toxcore-c/jobs/173011835

its all errors after the first error.
(search for "cannot find -lrt" on the travis page)

why is this so complicated to build?

**Comment by zoff99** [comment]
can you attach the
/home/travis/cache/ivy2/local/org.toktok/tox4j-c_2.11/0.1.0-SNAPSHOT/jars/tox4j-c_2.11.jar
from that travis build somewhere to i can look at it?

**Comment by zoff99** [comment]
i cant compile it. need some help?

**Comment by iphydf** [comment]
> this is your own travis build

My own travis build works. What does not work on your side? The library is created here: https://travis-ci.org/TokTok/jvm-toxcore-c/jobs/173011835#L949.

> why is this so complicated to build?

Because the various platforms we want to support look very different. We've been through several rounds of simplification. I've rewritten the build scripts from scratch at least three times, thinking it doesn't need to be so complicated, but it always turns out to need to handle all kinds of special cases.

> its all errors after the first error

Although it does say "error" a lot, these are actually warnings that are printed to stderr. SBT thinks they are errors, because it has no clue what we're actually executing there.

What is *your* error? Can you post *your* build log? Because mine works.

By the way, you should use the branch I'm trying to pull in #8. The master branch works with irungentoo/toxcore, not with the most recent toktok/toxcore. You need #8 for that. @wiiaam or someone else needs to approve.

**Comment by zoff99** [comment]
oh ok. i will try with #8 because i use c-toxcore from toktok.
i am trying to build Antox fully from source with the new tox4j. i tought it would be a quick thing :-)

here is my build hack:
https://circleci.com/gh/zoff99/Antox/156

the step: "buildscripts/04_build" never runs through

```
[error] Error (java.lang.RuntimeException: Nonzero exit value: 1) while executing: clang++ -c -o /home/ubuntu/Antox/jvm-toxcore-c/target/x86_64-linux/objects/ToxCore/connection.o /home/ubuntu/Antox/jvm-toxcore-c/src/main/cpp/ToxCore/connection.cpp -I/home/ubuntu/cache/usr/include -isystem/home/ubuntu/cache/usr/include -ggdb3 -Wall -Wextra -pedantic -fcolor-diagnostics -fPIC -I/home/ubuntu/Antox/jvm-toxcore-c/src/main/cpp -I/home/ubuntu/Antox/jvm-toxcore-c/target/x86_64-linux/src_managed -I/usr/lib/jvm/java-8-oracle/include -I/usr/lib/jvm/java-8-oracle/include/linux -pthread -I/home/ubuntu/cache/usr/include -fno-exceptions -fno-rtti -DGOOGLE_PROTOBUF_NO_RTTI -DGTEST_HAS_RTTI=0 -std=c++1y -includecpp14compat.h
[error] /home/ubuntu/Antox/jvm-toxcore-c/src/main/cpp/ToxAv/generated/enums.cpp:58:11: warning: enumeration value 'TOXAV_FRIEND_CALL_STATE_NONE' not handled in switch [-Wswitch]
[error]   switch (valueOf)
[error]           ^
[error] /home/ubuntu/Antox/jvm-toxcore-c/src/main/cpp/ToxAv/generated/enums.cpp:90:11: warning: enumeration value 'TOXAV_FRIEND_CALL_STATE_NONE' not handled in switch [-Wswitch]
[error]   switch (arg)
[error]           ^
[error] 2 warnings generated.
```

**Comment by iphydf** [comment]
Ok, the error is:
```
[error] In file included from /home/ubuntu/Antox/jvm-toxcore-c/src/main/cpp/ToxCore/interaction.cpp:1:
[error] In file included from /home/ubuntu/Antox/jvm-toxcore-c/src/main/cpp/ToxCore/ToxCore.h:11:
[error] In file included from /home/ubuntu/Antox/jvm-toxcore-c/src/main/cpp/tox/core.h:46:
[error] /home/ubuntu/Antox/jvm-toxcore-c/src/main/cpp/tox/generated/core.h:2:1: error: non-type template argument of type 'void (Tox *, tox_file_chunk_request_cb *)' cannot be converted to a value of type 'void (*)(Tox *, void (*)(Tox *, unsigned int, unsigned int, unsigned long, unsigned long, void *), void *)'
[error] CALLBACK (file_chunk_request)
[error] ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[error] /home/ubuntu/Antox/jvm-toxcore-c/src/main/cpp/tox/core.h:45:82: note: expanded from macro 'CALLBACK'
[error] #define CALLBACK(NAME)  using callback_##NAME = detail::cb<Tox, tox_##NAME##_cb, tox_callback_##NAME>;
[error]                                                                                  ^~~~~~~~~~~~~~~~~~~
[error] <scratch space>:27:1: note: expanded from here
[error] tox_callback_file_chunk_request
[error] ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[error] /home/ubuntu/Antox/jvm-toxcore-c/src/main/cpp/tox/common.h:116:53: note: template parameter is declared here
[error]     template<typename Subsystem, typename Sig, void Set (Subsystem *, Sig, void *)>
```

This is because you're using master, which not compatible with c-toxcore at the moment. Antox won't build with jvm-toxcore-c, either, because some API changed. I've asked @wiiaam to review the API changes.

You can use jvm-toxcore-c master with c-toxcore 0.0.1 and possibly some later 0.0.x versions. It won't work with 0.1.x.

**Comment by iphydf** [comment]
You can see the API changes here: https://github.com/TokTok/jvm-toxcore-api/pull/1/files.

**Comment by zoff99** [comment]
i think i can fix antox to the api changes. as long as i get a .jar and .so file :-)
i already changed kaliumjni to sodiumjni as a first step.

i will wait then for #8 to get merged. you think it will happen in the next days or week?

**Comment by iphydf** [comment]
I think so. @wiiaam?

**Comment by zoff99** [comment]
i talked to wiiaam a few days ago in IRC. seems to have little time for antox now.
i can start with it, and wiiaam can just fix my bad style. that should work

**Comment by zoff99** [comment]
now thats solved. yet it's very complex to compile. should be easier

**Comment by iphydf** [comment]
It's not possible to be solved, because it's still waiting for #8 to be reviewed and merged.

**Comment by iphydf** [comment]
(Read: please review the PR)

**Comment by zoff99** [comment]
i am trying to check the PR. it's so bad to build
